name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-test-pack-publish:
    runs-on: ubuntu-latest #windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./src

      - name: Build
        run: dotnet build --no-restore --configuration Release /p:Version=0.0.0.$GITHUB_RUN_NUMBER
        working-directory: ./src
      
      # Integration tests should not run in parallel as it would cause issues with the shared MS SQL docker container.
      # Therefore, we run them sequentially.
      - name: "Test: ConcurrentChunking.Tests"
        run: dotnet test --no-build --configuration Release --verbosity normal
        working-directory: ./src/tests/ConcurrentChunking.Tests

      - name: "Test: ConcurrentChunking.DependencyInjection.Tests"
        run: dotnet test --no-build --configuration Release --verbosity normal
        working-directory: ./src/tests/ConcurrentChunking.DependencyInjection.Tests

      - name: "Test: ConcurrentChunking.Linq.Tests"
        run: dotnet test --no-build --configuration Release --verbosity normal
        working-directory: ./src/tests/ConcurrentChunking.Linq.Tests

      - name: "Test: ConcurrentChunking.IntegrationTests"
        run: dotnet test --no-build --configuration Release --verbosity normal
        working-directory: ./src/tests/ConcurrentChunking.IntegrationTests

      - name: "Test: ConcurrentChunking.Linq.IntegrationTests"
        run: dotnet test --no-build --configuration Release --verbosity normal
        working-directory: ./src/tests/ConcurrentChunking.Linq.IntegrationTests

      - name: Pack NuGet package
        run: dotnet pack --no-build --configuration Release -p:PackageVersion=1.0.0-prerelease.$GITHUB_RUN_NUMBER
        working-directory: ./src

      - name: Publish to NuGet
        if: github.ref == 'refs/heads/main'
        run: dotnet nuget push ./**/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
        working-directory: ./src
