name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-test-pack-publish:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./src

      - name: Build
        run: dotnet build --no-restore --configuration Release
        working-directory: ./src

      - name: Test
        run: dotnet test --no-build --configuration Release --verbosity normal
        working-directory: ./src

      - name: Pack NuGet package
        run: dotnet pack --no-build --configuration Release --output ./nupkgs
        working-directory: ./src

      - name: Publish to NuGet
        if: github.ref == 'refs/heads/main'
        run: dotnet nuget push ./nupkgs/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
        working-directory: ./src
